"""Generate V8__refresh_builtin_locales.sql from current src/i18n/locales/*.ts bundles.

The DB keeps a copy of the bundled locales (en-US / zh-CN) in `resources` so
the UI can list and activate them.  When the bundles gain new keys, the DB
copy has to be refreshed too — otherwise:
- Locales export "fill missing keys" pads with empty strings for the keys the
  DB row is missing, which is exactly the bug we're fixing here.
- Activating a built-in locale falls back to en-US for missing keys.

This script reads both bundles, emits one INSERT OR REPLACE-style UPDATE
statement per locale, and writes `V8__refresh_builtin_locales.sql`.
Re-run it whenever a key is added to zh-CN.ts or en-US.ts.

It is *not* auto-invoked by the build pipeline on purpose — we want humans to
read the diff before shipping a built-in-content update.
"""
import re
import json
import sys
import unicodedata
from pathlib import Path

ROOT = Path(r"C:\Users\19114\.minimax-agent-cn\projects\admin-suite")
TS_DIR = ROOT / "src" / "i18n" / "locales"
OUT = ROOT / "src-tauri" / "migrations" / "V8__refresh_builtin_locales.sql"


def parse_bundle(path: Path) -> dict:
    """Pull the inner object literal out of an `export default { ... }` file."""
    src = path.read_text(encoding="utf-8")
    body_start = src.find("export default {")
    body = src[body_start + len("export default {"):]
    depth = 0
    end = 0
    for i, ch in enumerate(body):
        if ch == "{":
            depth += 1
        elif ch == "}":
            if depth == 0:
                end = i
                break
            depth -= 1
    inner = body[:end]
    pair_re = re.compile(r"'([^']+)':\s*'((?:\\'|[^'])*)'")
    out: dict[str, str] = {}
    for m in pair_re.finditer(inner):
        k = m.group(1)
        v = m.group(2).replace("\\'", "'").replace("\\\\", "\\")
        out[k] = v
    return out


def esc(s: str) -> str:
    """Escape a string for a single-quoted SQL literal."""
    return s.replace("'", "''")


bundles = {
    "en-US": ("English", parse_bundle(TS_DIR / "en-US.ts")),
    "zh-CN": ("简体中文", parse_bundle(TS_DIR / "zh-CN.ts")),
}

lines: list[str] = []
lines.append("-- V8 — Refresh built-in locales with the current src/i18n/locales/*.ts content.")
lines.append("--")
lines.append("-- Why this migration exists:")
lines.append("--   V2 seeded the original en-US / zh-CN rows with ~150 keys.  Every subsequent")
lines.append("--   addition to the bundled locales (Settings, Backups, Command Palette, and all the")
lines.append("--   per-page labels) only landed in the .ts files, never in the DB.  That left the")
lines.append("--   DB copy stale, so activating a built-in locale fell back to en-US for the new")
lines.append("--   keys and the Locales export \"fill missing keys\" feature padded with empty strings.")
lines.append("--")
lines.append("-- This file is generated by `scripts/gen-v8-locale-refresh.py` from the live bundles.")
lines.append("-- Re-run that script whenever a key is added/renamed in en-US.ts or zh-CN.ts.")
lines.append("--")
lines.append("-- We deliberately use UPDATE (not REPLACE) so the existing row id is preserved — that")
lines.append("-- keeps role_menus references and the locale active pointer valid.  built_in=1 +")
lines.append("-- source='builtin' are preserved.  Users who customized a built-in locale can re-import")
lines.append("-- their own copy under a different code; this only refreshes the rows we ship.")
lines.append("")
lines.append("-- Sentinel: re-running this migration must be a no-op once it's been applied (the UPDATE")
lines.append("-- just rewrites the same content).  The migrator checks SHA-256 of the file, so any")
lines.append("-- future edit to a key forces a new V{n} migration rather than silently mutating V8.")
lines.append("")

for code, (label, messages) in bundles.items():
    content = json.dumps(
        {"id": code, "label": label, "messages": messages},
        ensure_ascii=False,
        separators=(",", ":"),
    )
    # JSON on one line keeps the SQL compact and grep-friendly.
    lines.append(
        f"UPDATE resources SET name = '{esc(label)}', content = '{esc(content)}', "
        f"updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') "
        f"WHERE resource_type = 'locale' AND code = '{code}' AND built_in = 1;"
    )
    lines.append("")

OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {OUT}")
for code, (label, msgs) in bundles.items():
    print(f"  {code:6}  {label:8}  {len(msgs)} keys")